export const CONTRACT_ABI = [
  "function startGame() external returns (uint256 gameId)",
  "function requestRevealCell(uint256 gameId, uint8 cellIndex) external",
  "function completeReveal(bool isMine, bytes calldata decryptionProof) external",
  "function cancelReveal() external",
  "function getCellState(uint256 gameId, uint8 cellIndex) external view returns (uint8)",
  "function getAllCellStates(uint256 gameId) external view returns (uint8[25] memory states)",
  "function getGameInfo(uint256 gameId) external view returns (address player, uint256 startTime, uint256 endTime, uint8 revealedCount, uint8 safeRevealed, uint8 state)",
  "function getLeaderboardLength() external view returns (uint256)",
  "function getTopLeaderboard(uint256 count) external view returns (tuple(address player, uint256 clearTime, uint256 timestamp)[] memory)",
  "function hasActiveGame(address player) external view returns (bool, uint256)",
  "function hasPendingReveal(address player) external view returns (bool)",
  "function getPendingReveal(address player) external view returns (uint256 gameId, uint8 cellIndex, bytes32 handle)",
  "function minesInitialized() external view returns (bool)",
  "function gameCounter() external view returns (uint256)",
  "function GRID_SIZE() external view returns (uint8)",
  "function MINE_COUNT() external view returns (uint8)",
  "function CELL_PENDING() external view returns (uint8)",
  "event GameStarted(uint256 indexed gameId, address indexed player)",
  "event CellRevealRequested(uint256 indexed gameId, uint8 cellIndex, address indexed player, bytes32 handle)",
  "event CellRevealed(uint256 indexed gameId, uint8 cellIndex, bool isMine)",
  "event GameWon(uint256 indexed gameId, address indexed player, uint256 clearTime)",
  "event GameLost(uint256 indexed gameId, address indexed player)",
];
